### ISSUE TITLE
Error updating Kobo resources

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#1004]
After clicking the _Update Kobo resource_ button on a dataset we don't get properly updated the XLS file
CSV is updated successfully.

Updating Kobo resources

![k1](https://user-images.githubusercontent.com/3237309/228592931-d8630a55-9a49-4066-ac2f-481c09067115.png)

![k2](https://user-images.githubusercontent.com/3237309/228592981-a16245ac-12e1-4b8a-8917-d09ad66c3126.png)

XLS do not change timestamp

![k3](https://user-images.githubusercontent.com/3237309/228592996-0617e3d8-2182-4449-bac5-f45ede036243.png)

CSV change timestamp

![k4](https://user-images.githubusercontent.com/3237309/228593056-37c99e35-ccf0-4793-9f6b-95fe108b15b7.png)

**Comment by avdata99** [comment]
INFO [ckanext.unhcr.kobo.filters] Processing kobo filters for resource {'kobo_export_id': 'e3URJV4YYcnhsLCNyS5o3J', 'kobo_asset_id': ' XXX', 'kobo_download_status': 'complete', 'kobo_download_attempts': 1, 'kobo_last_updated': '2023-02-20T21:26:04.170555', 'kobo_filter_fields_from_all_versions': True, 'kobo_filter_group_sep': '/', 'kobo_filter_fields': [], 'kobo_filter_query': None, 'kobo_filter_multiple_select': 'both', 'kobo_filter_hierarchy_in_labels': True, 'kobo_filter_language': '_xml'}
 INFO [ckanext.unhcr.jobs] Preparing export {'fields_from_all_versions': True, 'group_sep': '/', 'hierarchy_in_labels': True, 'multiple_select': 'both', 'lang': '_xml', 'fields': [], 'query': None}
 ERROR [ckan.lib.jobs] Job b454e329-41f3-4b5d-8bdc-79f4710bfa40 on worker rq:worker:1a36ee6e1bb74c7a87b356efbc35023d raised an exception: Invalid export format: xlsx
 Traceback (most recent call last):
 File "/usr/lib/python3.8/site-packages/rq/worker.py", line 812, in perform_job
 rv = job.perform() |
 File "/usr/lib/python3.8/site-packages/rq/job.py", line 588, in perform
 self._result = self._execute()|
 File "/usr/lib/python3.8/site-packages/rq/job.py", line 594, in _execute
 return self.func(*self.args, **self.kwargs)
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/jobs.py", line 251, in update_kobo_resource
 export = survey.create_export(**export_params)
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/kobo/api.py", line 264, in create_export
 raise KoBoSurveyError('Invalid export format: {}'.format(dformat))
 ckanext.unhcr.kobo.exceptions.KoBoSurveyError: Invalid export format: xlsx
