### ISSUE TITLE
Fix get_data_deposit function

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-unhcr#103]
# Overview

We have `get_data_deposit` function which called a lot especially for curation UI (datasets listing):

```
def get_data_deposit():
    try:
        context = {'model': model, 'ignore_auth': True}
        return toolkit.get_action('organization_show')(context, {'id': 'data-deposit'})
    except toolkit.ObjectNotFound:
        log.error('Data Deposit is not created')
        return {'id': 'data-deposit'}
```

A naive caching solution works fine but make tests failing:

```
deposit = None
def get_data_deposit():
    global deposit
    if not deposit:
        try:
            deposit =  toolkit.get_action('organization_show')(
                {'model': model, 'ignore_auth': True}, {'id': 'data-deposit'})
        except toolkit.ObjectNotFound:
            log.error('Data deposit is not created')
            return {'id': 'data-deposit'}
    return deposit
```
with an error:

```
ERROR: ckanext.unhcr.tests.test_controllers.TestDepositedDatasetController.test_activites_not_shown_on_normal_dataset('depositor',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/usr/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/srv/app/src_extensions/ckanext-unhcr/ckanext/unhcr/tests/test_controllers.py", line 62, in setup
    user=self.creator)
  File "/usr/lib/python2.7/site-packages/factory/base.py", line 80, in __call__
    return cls.create(**kwargs)
  File "/usr/lib/python2.7/site-packages/factory/base.py", line 453, in create
    return cls._generate(True, attrs)
  File "/usr/lib/python2.7/site-packages/factory/base.py", line 378, in _generate
    obj = cls._prepare(create, **attrs)
  File "/usr/lib/python2.7/site-packages/factory/base.py", line 358, in _prepare
    return cls._create(target_class, *args, **kwargs)
  File "/srv/app/src/ckan/ckan/tests/factories.py", line 336, in _create
    **kwargs)
  File "/srv/app/src/ckan/ckan/tests/helpers.py", line 109, in call_action
    return logic.get_action(action_name)(context=context, data_dict=kwargs)
  File "/srv/app/src/ckan/ckan/logic/__init__.py", line 457, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src/ckan/ckan/logic/action/create.py", line 176, in package_create
    raise ValidationError(errors)
ValidationError: {'owner_org': ['Invalid data deposit']}
```

PS.
Additional problem that first failed tests make all following tests fail with an error below. It complicates diagnostics. 

```
DetachedInstanceError: Instance <Revision at 0x7f229c0c8f10> is not bound to a Session; attribute refresh operation cannot proceed
```

**Comment by roll** [comment]
E.g. we can disable caching for testing environment if ckan has something like `NODE_ENV=test` env variable

**Comment by roll** [comment]
Other solution here - start using `data-deposit` as a hard-coded name for data deposit. Most of the `get_data_deposit` calls are needed just to check for `deposit.name`.

 We anyway use hard-coded `deposited-dataset` type so probably it will not hurt to hard-code another string (or introduce some constants).
