### ISSUE TITLE
Exception when starting up prod CKAN container

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#278]
```
 17 ckan_1        | Traceback (most recent call last):
 18 ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
 19 ckan_1        |     return loadobj(APP, uri, name=name, **kw)
 20 ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
 21 ckan_1        |     return context.create()
 22 ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
 23 ckan_1        |     return self.object_type.invoke(self)
 24 ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
 25 ckan_1        |     return fix_call(context.object, context.global_conf, **context.local_conf)
 26 ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
 27 ckan_1        |     val = callable(*args, **kw)
 28 ckan_1        |   File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 58, in make_app
 29 ckan_1        |     **app_conf)
 30 ckan_1        |   File "/srv/app/src/ckan/ckan/config/middleware/pylons_app.py", line 121, in make_pylons_stack
 31 ckan_1        |     who_parser.parse(open(app_conf['who.config_file']))
 32 ckan_1        |   File "/usr/lib/python2.7/site-packages/repoze/who/config.py", line 86, in parse
 33 ckan_1        |     obj = self._makePlugin(name, IPlugin, options)
 34 ckan_1        |   File "/usr/lib/python2.7/site-packages/repoze/who/config.py", line 40, in _makePlugin
 35 ckan_1        |     obj = _resolve(name)
 36 ckan_1        |   File "/usr/lib/python2.7/site-packages/repoze/who/config.py", line 23, in _resolve
 37 ckan_1        |     return EntryPoint.parse('x=%s' % name).resolve()
 38 ckan_1        |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
 39 ckan_1        |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
 40 ckan_1        |   File "/srv/app/src/pysaml2/src/saml2/s2repoze/plugins/sp.py", line 29, in <module>
 41 ckan_1        |     from saml2.client_base import ECP_SERVICE
 42 ckan_1        |   File "/srv/app/src/pysaml2/src/saml2/client_base.py", line 11, in <module>
 43 ckan_1        |     from saml2.entity import Entity
 44 ckan_1        |   File "/srv/app/src/pysaml2/src/saml2/entity.py", line 10, in <module>
 45 ckan_1        |     from saml2.metadata import ENDPOINTS
 46 ckan_1        |   File "/srv/app/src/pysaml2/src/saml2/metadata.py", line 2, in <module>
 47 ckan_1        |     from saml2.algsupport import algorithm_support_in_metadata
 48 ckan_1        |   File "/srv/app/src/pysaml2/src/saml2/algsupport.py", line 2, in <module>
 49 ckan_1        |     from saml2.sigver import get_xmlsec_binary
 50 ckan_1        |   File "/srv/app/src/pysaml2/src/saml2/sigver.py", line 8, in <module>
 51 ckan_1        |     from OpenSSL import crypto
 52 ckan_1        |   File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
 53 ckan_1        |     from OpenSSL import crypto, SSL
 54 ckan_1        |   File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 15, in <module>
 55 ckan_1        |     from OpenSSL._util import (
 56 ckan_1        |   File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
 57 ckan_1        |     from cryptography.hazmat.bindings.openssl.binding import Binding
 58 ckan_1        |   File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 16, in <module>
 59 ckan_1        |     from cryptography.hazmat.bindings._openssl import ffi, lib
 60 ckan_1        | ImportError: Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found
```

**Comment by er-shrey** [comment]
What was the exact issue with this? any root cause?

**Comment by amercader** [comment]
@er-shrey if it helps here's the commit that fixed this in another repo:

> ckanext-saml2 requires pysaml2==4.0.0 that requires pyOpenSSL==19.1.0,
which has an unpinned cryptography requirement (>=2.8).

> crytography==2.8 works fine but cryptography==2.9, which was released
13 days ago, fails with the exception in the issue linked.

> I'm not sure if that's pyOpenSSL's fault because the Alpine image we are
using uses libressl, which might not be supported.
