### ISSUE TITLE
CKAN 2.9: `AttributeError: 'bool' object has no attribute 'rstrip'` when logging out

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#542]
I don't have a reliable way to reproduce this error yet, but I've managed to throw this twice while trying to log out

![Screenshot_2021-04-23 AttributeError 'bool' object has no attribute 'rstrip' Werkzeug Debugger](https://user-images.githubusercontent.com/6025893/115899821-22ed0200-a457-11eb-9cc7-0dc1b98b7804.png)

Step 1 is find a repro case.

**Comment by chris48s** [comment]
```
[werkzeug] 172.24.0.1 - - [10/May/2021 10:47:01] "GET /api/i18n/en HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/srv/app/src_extensions/ckan/ckan/views/user.py", line 477, in logout
    parse_url=True)
  File "/srv/app/src_extensions/ckan/ckan/lib/helpers.py", line 217, in redirect_to
    _url = url_for(*uargs, **kw)
  File "/srv/app/src_extensions/ckanext-unhcr/ckanext/unhcr/plugin.py", line 91, in url_for
    url = _url_for(*args, **kw)
  File "/srv/app/src_extensions/ckan/ckan/lib/helpers.py", line 355, in url_for
    my_url = _url_for_flask(*args, **kw)
  File "/srv/app/src_extensions/ckan/ckan/lib/helpers.py", line 436, in _url_for_flask
    u'{}={}'.format(quote(key), quote(val)))
  File "/usr/lib/python2.7/urllib.py", line 1304, in quote
    if not s.rstrip(safe):
AttributeError: 'bool' object has no attribute 'rstrip'
```

**Comment by chris48s** [comment]
This is happening if `kwargs == {'__no_cache__': True}` in `url_for()`
think this one needs fixing in core.

https://github.com/ckan/ckan/blob/e6f2f3060da8fb11201de8d3a1c289a10f028cc7/ckan/lib/helpers.py#L442-L448

Roughly, if you make it

```diff
- query_args.append(u'{}={}'.format(quote(key), quote(val)))
+ query_args.append(u'{}={}'.format(quote(key), quote(str(val))))
```

that seems to fix it. So probably core patch/upstream PR for this

**Comment by chris48s** [comment]
There's a core patch for this in the deploy repo PR https://github.com/okfn/docker-ckan-unhcr-aws/pull/35/commits/36e81cb707da61d3f8fcc6c241c5913f249c1899
and I've submitted a PR to core at https://github.com/ckan/ckan/pull/6099

**Comment by chris48s** [comment]
handled by core patch
