### ISSUE TITLE
CKAN 2.9: `AttributeError: 'NoneType' object has no attribute 'transaction'` editing resource

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#559]
Steps to reproduce

1. Create a dataset
2. Add a resource to it
3. Edit the resource
4. Replace the uploaded file with a different one (can have the same name or different name - throws either way)

Stacktrace:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/srv/app/src_extensions/ckan/ckan/views/resource.py", line 371, in post
    get_action(u'resource_update')(context, data)
  File "/srv/app/src_extensions/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src_extensions/ckanext-unhcr/ckanext/unhcr/actions.py", line 863, in resource_update
    resource = up_func(context, data_dict)
  File "/srv/app/src_extensions/ckan/ckan/logic/action/update.py", line 104, in resource_update
    updated_pkg_dict = _get_action('package_update')(context, pkg_dict)
  File "/srv/app/src_extensions/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src_extensions/ckanext-unhcr/ckanext/unhcr/actions.py", line 60, in package_update
    dataset = update_core.package_update(context, data_dict)
  File "/srv/app/src_extensions/ckan/ckan/logic/action/update.py", line 346, in package_update
    model.repo.commit()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 464, in _prepare_impl
    stx = self.session.transaction
AttributeError: 'NoneType' object has no attribute 'transaction'
```

**Comment by chris48s** [comment]
Is this related to https://github.com/ckan/ckan/issues/5563 ?

They're not the _exact_ same error. We're throwing it interactively when `member_obj.save()` is called in `package_owner_org_update` whereas they are seeing it when `model.repo.commit()` is called in `package_update` when the datapusher pushes. They're both `AttributeError: 'NoneType' object has no attribute 'transaction'` manifesting when uploading a new file to an existing resource though :thinking:

**Comment by chris48s** [comment]
This reproduces if I completely disable our custom `package_update` action

**Comment by chris48s** [comment]
This is slightly different from https://github.com/ckan/ckan/issues/5597
In https://github.com/ckan/ckan/issues/5597 they are hitting this in `task_status_update` after a datapusher push. In our case, the datapusher is ok but we are hitting this same stacktrace but we are triggering it interactively.

**Comment by chris48s** [comment]
Hmm. So maybe this is the same underlying issue as https://github.com/ckan/ckan/issues/5597
We are hitting it interactively, but if I disable datapusher that resolves it so I guess it probably is the same issue

**Comment by chris48s** [comment]
handled by core patch

**Comment by ChristianF88** [comment]
Hi there,

I wanted to let you know that this issue seems to be still not fixed or has appeared again. I am using a fresh source install of ckan 2.9.7 on debian 11 and copy-pasted the test data creation commands (https://docs.ckan.org/en/2.9/maintaining/getting-started.html#creating-test-data) into the terminal.

here's the output
```
(default) root@ckan:/usr/lib/ckan/default/src/ckanext-eaw_theme# ckan -c /etc/ckan/default/ckan.ini seed basic
ckan -c /etc/ckan/default/ckan.ini seed family
ckan -c /etc/ckan/default/ckan.ini seed gov
ckan -c /etc/ckan/default/ckan.ini seed hierarchy
ckan -c /etc/ckan/default/ckan.ini seed search
ckan -c /etc/ckan/default/ckan.ini seed translations
ckan -c /etc/ckan/default/ckan.ini seed user
ckan -c /etc/ckan/default/ckan.ini seed vocabs
2022-11-29 10:28:21,916 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2022-11-29 10:28:21,917 INFO  [ckan.config.environment] Loading static files from public
2022-11-29 10:28:22,184 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:23,200 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:23,279 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2022-11-29 10:28:23,322 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2022-11-29 10:28:23,346 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2022-11-29 10:28:24,857 DEBUG [ckanext.xloader.plugin] Skipping xloading resource 0f1f152e-183e-4a06-b3d8-b3ace1266406 because format "plain text" is not configured to be xloadered
2022-11-29 10:28:24,858 DEBUG [ckanext.xloader.plugin] Skipping xloading resource e8d51863-910f-4bf8-86b3-62f97bf83117 because format "JSON" is not configured to be xloadered
2022-11-29 10:28:27,267 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2022-11-29 10:28:27,269 INFO  [ckan.config.environment] Loading static files from public
2022-11-29 10:28:27,563 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:28,527 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:28,604 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2022-11-29 10:28:28,642 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2022-11-29 10:28:28,667 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2022-11-29 10:28:32,000 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2022-11-29 10:28:32,001 INFO  [ckan.config.environment] Loading static files from public
2022-11-29 10:28:32,267 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:33,191 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:33,272 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2022-11-29 10:28:33,312 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2022-11-29 10:28:33,337 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2022-11-29 10:28:33,877 DEBUG [ckanext.xloader.plugin] Skipping xloading resource ce61cd33-0432-469b-bbd8-fe0393148202 because format "DOC" is not configured to be xloadered
2022-11-29 10:28:33,885 DEBUG [ckanext.xloader.plugin] Submitting resource 12427fa0-9d51-4e43-82da-f724dd5dabfa to be xloadered
2022-11-29 10:28:34,013 DEBUG [ckanext.xloader.plugin] Skipping xloading resource ce61cd33-0432-469b-bbd8-fe0393148202 because format "DOC" is not configured to be xloadered
2022-11-29 10:28:34,018 DEBUG [ckanext.xloader.plugin] Submitting resource 12427fa0-9d51-4e43-82da-f724dd5dabfa to be xloadered
2022-11-29 10:28:34,028 ERROR [ckan.logic] Could not find resource 12427fa0-9d51-4e43-82da-f724dd5dabfa after all
2022-11-29 10:28:34,039 INFO  [ckanext.xloader.action] Added background job 9c9a8355-2326-4011-ae60-ddbb8caa2539 to queue "default"
2022-11-29 10:28:34,039 DEBUG [ckanext.xloader.action] Enqueued xloader job=9c9a8355-2326-4011-ae60-ddbb8caa2539 res_id=12427fa0-9d51-4e43-82da-f724dd5dabfa
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/seed.py", line 42, in gov
    CreateTestData.create_gov_test_data()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/create_test_data.py", line 39, in create_gov_test_data
    cls.create_arbitrary(gov_items, extra_user_names=extra_users)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/create_test_data.py", line 250, in create_arbitrary
    model.repo.commit_and_remove()
  File "/usr/lib/ckan/default/src/ckan/ckan/model/__init__.py", line 180, in commit_and_remove
    self.session.commit()
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 464, in _prepare_impl
    stx = self.session.transaction
AttributeError: 'NoneType' object has no attribute 'transaction'
2022-11-29 10:28:36,115 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2022-11-29 10:28:36,116 INFO  [ckan.config.environment] Loading static files from public
2022-11-29 10:28:36,369 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:37,310 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:37,385 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2022-11-29 10:28:37,424 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2022-11-29 10:28:37,450 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2022-11-29 10:28:41,573 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2022-11-29 10:28:41,574 INFO  [ckan.config.environment] Loading static files from public
2022-11-29 10:28:41,838 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:42,800 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:42,870 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2022-11-29 10:28:42,907 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2022-11-29 10:28:42,932 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2022-11-29 10:28:43,572 DEBUG [ckanext.xloader.plugin] Submitting resource f23844e0-730d-4e36-bb10-b2db831aaef0 to be xloadered
2022-11-29 10:28:43,689 DEBUG [ckanext.xloader.plugin] Submitting resource f23844e0-730d-4e36-bb10-b2db831aaef0 to be xloadered
2022-11-29 10:28:43,697 ERROR [ckan.logic] Could not find resource f23844e0-730d-4e36-bb10-b2db831aaef0 after all
2022-11-29 10:28:43,698 DEBUG [ckanext.xloader.plugin] Skipping xloading resource 42ed559a-063a-413e-a973-624b8a940811 because format "DOC" is not configured to be xloadered
2022-11-29 10:28:43,786 INFO  [ckanext.xloader.action] Added background job 63ef937c-c551-4053-be0e-f8a3cf4fe3d6 to queue "default"
2022-11-29 10:28:43,786 DEBUG [ckanext.xloader.action] Enqueued xloader job=63ef937c-c551-4053-be0e-f8a3cf4fe3d6 res_id=f23844e0-730d-4e36-bb10-b2db831aaef0
2022-11-29 10:28:43,796 DEBUG [ckanext.xloader.plugin] Skipping xloading resource 42ed559a-063a-413e-a973-624b8a940811 because format "DOC" is not configured to be xloadered
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/seed.py", line 34, in search
    CreateTestData.create_search_test_data()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/create_test_data.py", line 35, in create_search_test_data
    cls.create_arbitrary(search_items)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/create_test_data.py", line 250, in create_arbitrary
    model.repo.commit_and_remove()
  File "/usr/lib/ckan/default/src/ckan/ckan/model/__init__.py", line 180, in commit_and_remove
    self.session.commit()
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 464, in _prepare_impl
    stx = self.session.transaction
AttributeError: 'NoneType' object has no attribute 'transaction'
2022-11-29 10:28:45,924 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2022-11-29 10:28:45,924 INFO  [ckan.config.environment] Loading static files from public
2022-11-29 10:28:46,172 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:47,104 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:47,180 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2022-11-29 10:28:47,221 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2022-11-29 10:28:47,246 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2022-11-29 10:28:50,010 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2022-11-29 10:28:50,011 INFO  [ckan.config.environment] Loading static files from public
2022-11-29 10:28:50,257 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:51,169 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:51,242 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2022-11-29 10:28:51,280 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2022-11-29 10:28:51,302 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
Created user tester with password tester and apikey tester
2022-11-29 10:28:53,672 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2022-11-29 10:28:53,673 INFO  [ckan.config.environment] Loading static files from public
2022-11-29 10:28:53,936 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:54,851 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-11-29 10:28:54,922 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2022-11-29 10:28:54,963 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2022-11-29 10:28:54,986 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
```

**Comment by amercader** [comment]
@ChristianF88 Try to deactivate the xloader plugins before running the seed command

Also please open a new issue in the main ckan/ckan repo if you still have problems

**Comment by ChristianF88** [comment]
@amercader Thanks for the input. Unfortunately that didn't work. However I figured out that [Xloader](https://github.com/ckan/ckanext-xloader) is causing the issue. 
It's caused by the fact, that the ReadMe instructs one to pip install xloader from PyPi. However the Xloader package on PyPi is version 0.8.0.

Running a pip install on the latest version (0.11.0) directly from github fixed the problem.

```
pip install git+https://github.com/ckan/ckanext-xloader.git@0.11.0
```

**Comment by amercader** [comment]
Thanks for flagging this @ChristianF88 , I just released the latest xloader version on Pypi
