### ISSUE TITLE
CKAN 2.9: Exception in dataset post-processing background job

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#567]
On the 2.9 branch, when adding a resource via the UI I get the following exception in the jobs worker log:

```
2021-05-26 10:11:56,535 ERROR [ckan.lib.jobs] Job b35bc7b2-c71b-4b71-a613-e991af1b6e8b on worker rq:worker:dc5f4929e30648a8891a088753fe0b91 raised an exception: Action package_show requires an authenticated user
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/lib/python2.7/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/lib/python2.7/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/srv/app/src_extensions/ckanext-unhcr/ckanext/unhcr/jobs.py", line 42, in process_dataset_on_update
    _process_dataset_fields(package_id)
  File "/srv/app/src_extensions/ckanext-unhcr/ckanext/unhcr/jobs.py", line 62, in _process_dataset_fields
    package = package_show({'job': True}, {'id': package_id})
  File "/srv/app/src_extensions/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src_extensions/ckan/ckan/logic/action/get.py", line 978, in package_show
    _check_access('package_show', context, data_dict)
  File "/srv/app/src_extensions/ckan/ckan/logic/__init__.py", line 313, in check_access
    raise NotAuthorized(msg)
NotAuthorized: Action package_show requires an authenticated user
```

Which makes sense, because we are not passing `user` or `ignore_auth` in the context [here](https://github.com/okfn/ckanext-unhcr/blob/5743888dee8608dd2754331a8f60c74e13f1349b/ckanext/unhcr/jobs.py#L62).
Adding `ignore_auth` makes this call work but if fails a bit further down when calling `package_update`

```
ERROR [ckan.lib.jobs] Job 92b31ec1-cbfd-4558-9a75-20318ac2bf45 on worker rq:worker:ac18d3a0847345c0b98628c462995731 raised an exception: User not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/lib/python2.7/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/lib/python2.7/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/srv/app/src_extensions/ckanext-unhcr/ckanext/unhcr/jobs.py", line 42, in process_dataset_on_update
    _process_dataset_fields(package_id)
  File "/srv/app/src_extensions/ckanext-unhcr/ckanext/unhcr/jobs.py", line 69, in _process_dataset_fields
    package_update({'job': True}, package)
  File "/srv/app/src_extensions/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src_extensions/ckanext-unhcr/ckanext/unhcr/actions.py", line 49, in package_update
    user_obj = _get_user_obj(context)
  File "/srv/app/src_extensions/ckanext-unhcr/ckanext/unhcr/actions.py", line 40, in _get_user_obj
    raise toolkit.ObjectNotFound("User not found")
NotFound: User not found
```

The fix is straight-forward, just add `{"ignore_auth": True}` but I wonder why haven't we hit that before? Maybe on 2.8  `c.user` was available when [auto-populating](https://github.com/ckan/ckan/blob/27f0b8cf52bb2140f16e2f09f3c42ed15e7e9b99/ckan/logic/__init__.py#L238) the context) and this is no longer the case in 2.9.

**Comment by chris48s** [comment]
fixes for this are WIP in https://github.com/okfn/ckanext-unhcr/pull/550

**Comment by chris48s** [comment]
In fact is this issue a straight dupe of https://github.com/okfn/ckanext-unhcr/issues/528 ?

**Comment by amercader** [comment]
Looks like it, closing
