### ISSUE TITLE
403 Forbidden: You don't have the permission to access the requested resource

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#608]
Getting a lot of these in the logs for UAT

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/srv/app/src/ckan/ckan/views/home.py", line 29, in before_request
    abort(403)
  File "/usr/lib/python2.7/site-packages/werkzeug/exceptions.py", line 774, in abort
    return _aborter(status, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/werkzeug/exceptions.py", line 755, in __call__
    raise self.mapping[code](*args, **kwargs)
Forbidden: 403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
```

I don't think "resource" is a resource in the CKAN sense. I think this is being thrown but a static asset request or something?
Can't reproduce in dev, don't have a reliable repro case for UAT yet either.

First job is to find a call that reliably throws this error so we can reproduce it.

**Comment by chris48s** [comment]
This is actually expected (and it is the CKAN resource). Failed resource previews fallback to calling `https://jsonpdataproxy.appspot.com` with a resource URL and that (correctly) throws a 403 on the resource. We don't want to pass data out to  a third party service.
