### ISSUE TITLE
Error downloading JSON resource from KoBo dataset

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#690]
To reproduce: Import a survey from KoBo and after publish try to download the JSON data
Environment: UAT Releases 3.1.3
Error:
<pre>
| 1631192141192 | 2021-09-09 12:55:41,192 ERROR [ckan.config.middleware.flask_app] 'Saml2AuthPlugin' object has no attribute 'abort'  |
| 1631192141192 | Traceback (most recent call last):                                                                              |
| 1631192141192 |   File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/blueprints/resource.py", line 32, in download                  |
| 1631192141192 |     toolkit.check_access(u'resource_download', context.copy(), {u'id': resource_id})                            |
| 1631192141192 |   File "/srv/app/src/ckan/ckan/logic/__init__.py", line 313, in check_access                                    |
| 1631192141192 |     raise NotAuthorized(msg)                                                                                    |
| 1631192141193 | ckan.logic.NotAuthorized                                                                                        |
| 1631192141193 | During handling of the above exception, another exception occurred:                                             |
| 1631192141193 | Traceback (most recent call last):                                                                              |
| 1631192141193 |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request                     |
| 1631192141193 |     rv = self.dispatch_request()                                                                                |
| 1631192141193 |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request                          |
| 1631192141193 |     return self.view_functions[rule.endpoint](**req.view_args)                                                  |
| 1631192141193 |   File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/utils.py", line 84, in view_wrapper                            |
| 1631192141193 |     return func(*args, **kwargs)                                                                                |
| 1631192141193 |   File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/blueprints/resource.py", line 36, in download                  |
| 1631192141193 |     return toolkit.abort(403, toolkit._(u'Not Authorized to download the resource')) |
| 1631192141193 |   File "/srv/app/src/ckan/ckan/lib/base.py", line 59, in abort |
| 1631192141193 |     result = item.abort(status_code, detail, headers, comment) |
<b>| 1631192141193 | AttributeError: 'Saml2AuthPlugin' object has no attribute 'abort'</b>
| 1631192141324 | 2021-09-09 12:55:41,324 INFO  [ckan.config.middleware.flask_app]  /dataset/5b6c7482-620c-492e-93ca-ae2fa79ee110/resource/287cad7a-52c4-4b2c-a381-bdf51ef581a2/download/aazsq29vrhjmofjgsfddv4_data.json render time 0.163 seconds |
</pre>

**Comment by avdata99** [comment]
New resources and updates ones works fine. Probably an error from the resource version changing
