### ISSUE TITLE
Error 500 on dataset

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#696]
Bug report: _I tried to manually create a dataset filling the mandatory field but as soon as I went to "Add data", I have an "internal server error"_

Dataset: https://ridl-uat.unhcr.org/deposited-dataset/test-push-manual-ds

**Comment by avdata99** [comment]
I approved my own test external user and I can validate a new external user have an error creating new deposit dataset

<pre>
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                        message                                                                        |
|---------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1631809360136 | 2021-09-16 16:22:40,136 INFO  [ckan.config.middleware.flask_app]  /data-container/data-deposit render time 0.492 seconds                              |
| 1631809443526 | 2021-09-16 16:24:03,526 INFO  [ckan.config.middleware.flask_app]  /deposited-dataset/new render time 0.919 seconds                                    |
| 1631809444441 | 2021-09-16 16:24:04,441 ERROR [ckan.config.middleware.flask_app] 'Saml2AuthPlugin' object has no attribute 'abort'                                    |
| 1631809444441 | Traceback (most recent call last):                                                                                                                    |
| 1631809444441 |   File "/srv/app/src/ckan/ckan/config/middleware/../../views/resource.py", line 305, in get                                                           |
| 1631809444441 |     check_access(                                                                                                                                     |
| 1631809444441 |   File "/srv/app/src/ckan/ckan/logic/__init__.py", line 313, in check_access                                                                          |
| 1631809444441 |     raise NotAuthorized(msg)                                                                                                                          |
| 1631809444441 | ckan.logic.NotAuthorized: User andres-vazquez not authorized to create resources on dataset cbaedfb9-7c15-4d9a-834f-7a7f190d7c08                      |
| 1631809444441 | During handling of the above exception, another exception occurred:                                                                                   |
| 1631809444441 | Traceback (most recent call last):                                                                                                                    |
| 1631809444441 |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request                                                           |
| 1631809444441 |     rv = self.dispatch_request()                                                                                                                      |
| 1631809444441 |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request                                                                |
| 1631809444441 |     return self.view_functions[rule.endpoint](**req.view_args)                                                                                        |
| 1631809444441 |   File "/usr/lib/python3.8/site-packages/flask/views.py", line 89, in view                                                                            |
| 1631809444441 |     return self.dispatch_request(*args, **kwargs)                                                                                                     |
| 1631809444441 |   File "/usr/lib/python3.8/site-packages/flask/views.py", line 163, in dispatch_request                                                               |
| 1631809444441 |     return meth(*args, **kwargs)                                                                                                                      |
| 1631809444441 |   File "/srv/app/src/ckan/ckan/config/middleware/../../views/resource.py", line 309, in get                                                           |
| 1631809444441 |     return base.abort(                                                                                                                                |
| 1631809444441 |   File "/srv/app/src/ckan/ckan/lib/base.py", line 59, in abort                                                                                        |
| 1631809444441 |     result = item.abort(status_code, detail, headers, comment)                                                                                        |
| 1631809444441 | AttributeError: 'Saml2AuthPlugin' object has no attribute 'abort'                                                                                     |
| 1631809444620 | 2021-09-16 16:24:04,620 INFO  [ckan.config.middleware.flask_app]  /deposited-dataset/my-new-test-dataset/resource/new render time 0.793 seconds       |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
</pre>

**Comment by avdata99** [comment]
The error is because 2 months ago we [skip not active datasets](https://github.com/okfn/ckanext-unhcr/commit/0d6b5a9ef70030ad4d0ed7e364da7a6bb09e38df).
And a new deposit dataset [is still draft](https://github.com/okfn/ckanext-unhcr/blob/release-3.1.4/ckanext/unhcr/helpers.py#L625) at the time before creating the first resource.
We need to be sure the status should be draft or active at that point.
