### ISSUE TITLE
Error deleting dataset

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#794]
Error trying to delete a dataset without `Geography`

Logs after deploying 3.1.7 to production

<pre>
1647273619956 2022-03-14 16:00:19,953 ERROR [ckan.config.middleware.flask_app] 'resources'

1647273619956 Traceback (most recent call last):
1647273619956 File "/srv/app/src/ckan/ckan/logic/action/delete.py", line 204, in resource_delete
1647273619956 pkg_dict = _get_action('package_update')(context, pkg_dict) 
1647273619956 File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped 
1647273619956 result = _action(context, data_dict, **kw)
1647273619956 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/actions.py", line 66, in package_update
1647273619956 dataset = up_func(context, data_dict) 
1647273619956 File "/srv/app/src/ckan/ckan/logic/action/update.py", line 312, in package_update 
1647273619956 raise ValidationError(errors) 
<b>1647273619956 ckan.logic.ValidationError: None - {'geographies': ['Missing value']} </b>

1647273619956 During handling of the above exception, another exception occurred: 
1647273619956 Traceback (most recent call last):
1647273619956 File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request 
1647273619956 rv = self.dispatch_request()
1647273619956 File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
1647273619956 return self.view_functions[rule.endpoint](**req.view_args)
1647273619956 File "/usr/lib/python3.8/site-packages/flask/views.py", line 89, in view
1647273619956 return self.dispatch_request(*args, **kwargs) 
1647273619956 File "/usr/lib/python3.8/site-packages/flask/views.py", line 163, in dispatch_request 
1647273619956 return meth(*args, **kwargs)
1647273619956 File "/srv/app/src/ckan/ckan/config/middleware/../../views/resource.py", line 467, in post
1647273619956 get_action(u'resource_delete')(context, {u'id': resource_id}) 
1647273619956 File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped 
1647273619956 result = _action(context, data_dict, **kw)
1647273619956 File "/srv/app/src/ckan/ckan/logic/action/delete.py", line 206, in resource_delete
1647273619956 errors = e.error_dict['resources'][-1]
<b>1647273619956 KeyError: 'resources' </b>
1647273620127 2022-03-14 16:00:20,126 INFO  [ckan.config.middleware.flask_app]  500 /dataset/aff-uscis-usa-2021/resource/15dff5c7-5c96-444e-9d41-820cb1c68922/delete render time 0.497 seconds

</pre>

**Comment by avdata99** [comment]
Fixed by assigning the default geography to all datasets
