### ISSUE TITLE
500 Errors

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#804]
500 error for users (probably) without permissions

Test URLs
 - https://ridl.unhcr.org/data-container/curacao
 - https://ridl.unhcr.org/dataset/cbi-di-curacao-pdm-tool_20210726_v3

**Comment by avdata99** [comment]
Query insight shows responses 200, 400 and 500

![image](https://user-images.githubusercontent.com/3237309/166423585-2b4d1c98-d85d-4526-8a2f-16d2de5c6f06.png)

**Comment by avdata99** [comment]
Error logs

<pre>
 2022-04-29 13:27:35,349 WARNI [saml2.client_base] The SAML service provider accepts unsigned SAML Responses and Assertions. This configuration is insecure. Consider setting want_assertions_signed, want_response_signed or want_assertions_or_response_signed configuration options. |
 2022-04-29 13:27:35,352 INFO [ckan.config.middleware.flask_app] 302 /user/saml2login render time 0.011 seconds |
 2022-04-29 13:27:36,515 WARNI [saml2.client_base] The SAML service provider accepts unsigned SAML Responses and Assertions. This configuration is insecure. Consider setting want_assertions_signed, want_response_signed or want_assertions_or_response_signed configuration options. |
 2022-04-29 13:27:36,618 INFO [ckan.config.middleware.flask_app] 302 /sso/post render time 0.111 seconds |
 2022-04-29 13:27:39,921 INFO [ckanext.unhcr.kobo.api] Getting KoBoToolbox resource: assets/XX.json |
 2022-04-29 13:27:39,922 INFO [ckanext.unhcr.kobo.api] Resource not cached: **USERNAME** :: assets/XX.json |
 2022-04-29 13:27:39,924 ERROR [ckan.config.middleware.flask_app] can only concatenate str (not "NoneType") to str |
 Traceback (most recent call last): |
 File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request |
 rv = self.dispatch_request() |
 File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request |
 return self.view_functions[rule.endpoint](**req.view_args) |
 File "/srv/app/src/ckan/ckan/config/middleware/../../views/dataset.py", line 501, in read |
 return base.render( |
 File "/srv/app/src/ckan/ckan/lib/base.py", line 151, in render |
 return flask_render_template(template_name, **extra_vars) |
 File "/usr/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template |
 return _render( |
 File "/usr/lib/python3.8/site-packages/flask/templating.py", line 120, in _render |
 rv = template.render(context) |
 File "/usr/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render |
 return original_render(self, *args, **kwargs) |
 File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render |
 return self.environment.handle_exception(exc_info, True) |
 File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception |
 reraise(exc_type, exc_value, tb) |
 File "/usr/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise |
 raise value.with_traceback(tb) |
 File "/srv/app/src/ckanext-scheming/ckanext/scheming/templates/scheming/package/read.html", line 3, in <module> |
 {%- set schema = h.scheming_get_dataset_schema(dataset_type) -%} |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/package/read.html", line 1, in <module> |
 {% ckan_extends %} |
 File "/srv/app/src/ckan/ckan/templates/package/read.html", line 1, in <module> |
 {% extends "package/read_base.html" %} |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/package/read_base.html", line 4, in <module> |
 {% set curation = h.get_deposited_dataset_user_curation_status(pkg_dict, c.userobj.id) %} |
 File "/srv/app/src/ckan/ckan/templates/package/read_base.html", line 1, in <module> |
 {% extends "package/base.html" %} |
 File "/srv/app/src/ckanext-hierarchy/ckanext/hierarchy/templates/package/base.html", line 1, in <module> |
 {% ckan_extends %} |
 File "/srv/app/src/ckan/ckan/templates/package/base.html", line 4, in <module> |
 {% set dataset_type = dataset_type or pkg.type or 'dataset' %} |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/page.html", line 1, in <module> |
 {% ckan_extends %} |
 File "/srv/app/src/ckan/ckan/templates/page.html", line 1, in <module> |
 {% extends "base.html" %} |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/base.html", line 1, in <module> |
 {% ckan_extends %} |
 File "/srv/app/src/ckanext-scheming/ckanext/scheming/templates/base.html", line 1, in <module> |
 {% ckan_extends %} |
 File "/srv/app/src/ckan/ckan/templates/base.html", line 106, in <module> |
 {%- block page %}{% endblock -%} |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/page.html", line 26, in <module> |
 {%- block content %} |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/page.html", line 29, in <module> |
 {% block main_content %} |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/page.html", line 51, in <module> |
 {% block primary %} |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/page.html", line 65, in <module> |
 {% block primary_content %}{{ super() }}{% endblock %} |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/page.html", line 65, in <module> |
 {% block primary_content %}{{ super() }}{% endblock %} |
 File "/srv/app/src/ckan/ckan/templates/page.html", line 89, in <module> |
 {% block page_header %} |
 File "/srv/app/src/ckan/ckan/templates/page.html", line 91, in <module> |
 {% if self.content_action() | trim %} |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/package/read_base.html", line 25, in <module> |
 {% if |
 File "/srv/app/src/ckan/ckan/lib/helpers.py", line 1328, in check_access |
 logic.check_access(action, context, data_dict) |
 File "/srv/app/src/ckan/ckan/logic/__init__.py", line 309, in check_access |
 logic_authorization = authz.is_authorized(action, context, |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/plugin.py", line 79, in unhcr_auth_wrapper |
 return func(action, context, data_dict) |
 File "/srv/app/src/ckan/ckan/authz.py", line 226, in is_authorized |
 return auth_function(context, data_dict) |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/auth.py", line 202, in package_kobo_update |
 survey = kobo_api.get_asset(kobo_asset_id) |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/kobo/api.py", line 111, in get_asset |
 asset = self._get(resource_url) |
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/kobo/api.py", line 60, in _get |
 response = requests.get(url, headers={'Authorization': 'Token ' + self.token}) |
 TypeError: can only concatenate str (not "NoneType") to str |
 2022-04-29 13:27:40,431 INFO [ckan.config.middleware.flask_app] 500 /dataset/cbi-di-curacao-pdm-tool_20210726_v3 render time 3.609 seconds

</pre>
