### ISSUE TITLE
Error 500 for /ckan-admin/containers/

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#906]
Logs
<pre>
 2022-11-02 16:49:34,600 ERROR [ckan.config.middleware.flask_app] 
 Traceback (most recent call last): 
 File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request 
 rv = self.dispatch_request() 
 File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request 
 return self.view_functions[rule.endpoint](**req.view_args) 
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/utils.py", line 84, in view_wrapper 
 return func(*args, **kwargs) 
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/blueprints/containers.py", line 23, in index 
 return toolkit.render('admin/containers.html') 
 File "/srv/app/src/ckan/ckan/lib/base.py", line 151, in render 
 return flask_render_template(template_name, **extra_vars) 
 File "/usr/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template 
 return _render( 
 File "/usr/lib/python3.8/site-packages/flask/templating.py", line 120, in _render 
 rv = template.render(context) 
 File "/usr/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render 
 return original_render(self, *args, **kwargs) 
 File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render 
 return self.environment.handle_exception(exc_info, True) 
 File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception 
 reraise(exc_type, exc_value, tb) 
 File "/usr/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise 
 raise value.with_traceback(tb) 
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/admin/containers.html", line 3, in <module> 
 {% set containers = h.data_containers_with_members_list(include_sysadmins=False) %} 
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/helpers.py", line 1286, in data_containers_with_members_list 
 containers = fn(context, {'include_sysadmins': include_sysadmins}) 
 File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped 
 result = _action(context, data_dict, **kw) 
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/actions.py", line 1799, in data_containers_with_members_list 
 duser = toolkit.get_action('user_show')(context, {'id': user[0]}) 
 File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped 
 result = _action(context, data_dict, **kw) 
 File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/actions.py", line 1587, in user_show 
 user = up_func(context, data_dict) 
 File "/srv/app/src/ckan/ckan/logic/action/get.py", line 1426, in user_show 
 raise NotFound 
 ckan.logic.NotFound 
 2022-11-02 16:49:34,732 INFO [ckan.config.middleware.flask_app] <b>500 /ckan-admin/containers/</b> render time 0.753 seconds 
</pre>

**Comment by avdata99** [comment]
Fixed [here](https://github.com/okfn/ckanext-unhcr/commit/1de12377f911e3bbb64e4f31babe59648045d3cf)
