### ISSUE TITLE
Push microdata works but show 500 error

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#923]
After push datasets to microdata library RIDL shows a 500 error
The data set is sent successfully, but this is not reported to the user.

Error log:

<pre>
ERROR [ckan.config.middleware.flask_app] get_path() missing 1 required positional argument: 'filename'
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/utils.py", line 84, in view_wrapper
return func(*args, **kwargs)
File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/blueprints/dataset.py", line 106, in publish_microdata
survey = _call_publish_action(
File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/blueprints/dataset.py", line 88, in _call_publish_action
return toolkit.get_action('package_publish_microdata')(context, data_dict)
File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
result = _action(context, data_dict, **kw)
File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/actions.py", line 210, in package_publish_microdata
file_path = helpers.get_resource_file_path(resource)
File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/helpers.py", line 1150, in get_resource_file_path
return upload.get_path(resource[u'id'])
TypeError: get_path() missing 1 required positional argument: 'filename'
2022-11-15 16:06:32,759 INFO [ckan.config.middleware.flask_app] 500 /dataset/d2fdb36c-aa2d-4ffa-a8de-24338fedc755/publish_microdata render time 0.234 seconds
</pre>

**Comment by avdata99** [comment]
S3 extension requires this parameter [7 years ago](https://github.com/keitaroinc/ckanext-s3filestore/commit/2395da3f443dd464a0db610676a5ba2b3c217d4b#diff-b81aeeb07a967c87be4e2fe519345b26762f2cd187f977f3f6c6b76bdc912e8aR203)

https://github.com/keitaroinc/ckanext-s3filestore/blob/main/ckanext/s3filestore/uploader.py#L356
