### ISSUE TITLE
Error with related datasets

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#925]
A user have error at dataset.read if the user has permissions on the dataset but not on its related datasets

<pre>
2022-11-23 13:11:24,223 INFO [ckan.config.middleware.flask_app] 404 Not Found: Dataset not found
2022-11-23 13:11:24,236 INFO [ckan.config.middleware.flask_app] 404 /dataset/bgr-protmon-2022-05-09 render time 0.022 seconds
2022-11-23 13:11:26,356 ERROR [ckan.config.middleware.flask_app] User XXXXX not authorized to read package b3f62933-289f-42ac-8c83-d81927701990
Traceback (most recent call last):
File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/templates/scheming/display_snippets/linked_datasets.html", line 2, in <module>
{% for dataset in h.get_linked_datasets_for_display(data[field.field_name]) %}
File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/helpers.py", line 411, in get_linked_datasets_for_display
dataset = toolkit.get_action('package_show')(context, {'id': id})
File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
result = _action(context, data_dict, **kw)
File "/srv/app/src/ckan/ckan/logic/action/get.py", line 978, in package_show
_check_access('package_show', context, data_dict)
File "/srv/app/src/ckan/ckan/logic/__init__.py", line 313, in check_access
raise NotAuthorized(msg)
ckan.logic.NotAuthorized: User XXXXX not authorized to read package b3f62933-289f-42ac-8c83-d81927701990
2022-11-23 13:11:26,427 INFO [ckan.config.middleware.flask_app] 500 /dataset/bgr-protmon-2022-05-09 render time 2.081 seconds
</pre>

**Comment by avdata99** [comment]
The related dataset is deposited
